#%RAML 1.0
title: Santest Author API
protocols:
 - HTTP

version: v1
baseUri: https://api.example.com

# Define the /authors resource
/authors:
  get:
    description: Retrieve a list of authors
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "authors": [
                  {
                    "id": 1,
                    "name": "J.K. Rowling",
                    "books": ["Harry Potter", "Fantastic Beasts"]
                  },
                  {
                    "id": 2,
                    "name": "George R.R. Martin",
                    "books": ["A Song of Ice and Fire", "Game of Thrones"]
                  }
                ]
              }

  post:
    description: Create a new author
    body:
      application/json:
        example: |
          {
            "name": "Agatha Christie",
            "books": ["Murder on the Orient Express", "And Then There Were None"]
          }
    responses:
      201:
        description: Author created successfully

# Define the /authors/{authorId} resource
/authors/{authorId}:
  get:
    description: Retrieve details of a specific author
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "name": "J.K. Rowling",
                "books": ["Harry Potter", "Fantastic Beasts"]
              }
